expenses/urls.py
from django.urls import path
from expenses import views


urlpatterns = [
    path('expenses', views.ExpenseListView.as_view(), name='list'),
    path('<int:pk>/detail/', views.ExpenseDetailView.as_view(), name='detail'),
    path('create/', views.ExpenseCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.ExpenseUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.ExpenseDeleteView.as_view(), name='delete'),

    path('category/', views.CategoryListView.as_view(), name="category_list"),
    path('category/<int:pk>/detail/', views.CategoryDetailView.as_view(), name="category_detail"),
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete')
]

main_app/urls.py
from django.urls import path
from .views import HomePage
from django.views import generic


urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('about/', generic.TemplateView.as_view(
        template_name="main_app/about.html"
    ), name='about')
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from expenses import urls as exp_urls
from main_app import urls as ms_urls
from profiles import urls as prof_urls
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('expenses/', include((exp_urls, 'expenses'))),
    path('', include((ms_urls, 'main_site'))),
    path('profiles/', include((prof_urls, 'profiles'))),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] \
                  + urlpatterns \
                  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from django.views import generic
from django.views.generic import DetailView


from profiles.models import CommonUserProfile


urlpatterns = [
    path('<int:pk>/', DetailView.as_view(
        template_name="profiles/profile.html",
        model=CommonUserProfile
    ), name='profile'),
]

expenses/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=100
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Expense(models.Model):
    name = models.CharField(
        max_length=255
    )

    amount = models.DecimalField(
        max_digits=7,
        decimal_places=2
    )

    timestamp = models.DateTimeField(
        auto_now_add=True
    )

    category = models.ForeignKey(
        to=Category,
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return f"{self.name} ({self.amount} BYN)"

main_app/models.py
from django.db import models

# Create your models here.

profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class BaseUserProfile(models.Model):
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE
    )
    avatar = models.ImageField(
        upload_to='profile'
    )

    class Meta:
        abstract = True


class CommonUserProfile(BaseUserProfile):
    pass


class PremiumUserProfile(BaseUserProfile):
    account = models.BigIntegerField(default=0)

expenses/forms.py
from django import forms
from .models import *


class ExpensesCreateForm(forms.ModelForm):

    class Meta:
        model = Expense
        exclude = ['timestamp']


class ExpenseUpdateForm(forms.ModelForm):

    class Meta:
        model = Expense
        fields = "__all__"


class CategoryCreateForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'


class CategoryUpdateForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = "__all__"

expenses/views.py
from .models import Expense, Category
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, CreateView, UpdateView
from expenses import forms


class ExpenseListView(ListView):
    template_name = "expenses/expenses_list.html"
    model = Expense


class ExpenseDetailView(DeleteView):
    template_name = "expenses/detail.html"
    model = Expense


class ExpenseCreateView(CreateView):
    template_name = 'expenses/create.html'
    model = Expense
    form_class = forms.ExpensesCreateForm
    success_url = reverse_lazy('expenses:list')


class ExpenseUpdateView(UpdateView):
    template_name = "expenses/update.html"
    model = Expense
    form_class = forms.ExpenseUpdateForm

    def get_success_url(self):
        return reverse_lazy(
            'expenses:detail', kwargs={'pk': self.kwargs['pk']}
        )


class ExpenseDeleteView(DeleteView):
    template_name = 'expenses/delete.html'
    model = Expense
    success_url = reverse_lazy('expenses:list')


class CategoryListView(ListView):
    template_name = "expenses/category.html"
    model = Category


class CategoryDetailView(DeleteView):
    template_name = 'expenses/category_detail.html'
    model = Category
    # success_url = reverse_lazy('expenses:category_detail')


class CategoryCreateView(CreateView):
    template_name = "expenses/category_create.html"
    model = Category
    form_class = forms.CategoryCreateForm
    success_url = reverse_lazy('expenses:category_list')


class CategoryUpdateView(UpdateView):
    template_name = "expenses/category_update.html"
    model = Category
    form_class = forms.CategoryUpdateForm

    def get_success_url(self):
        return reverse_lazy(
            'expenses:category_detail', kwargs={'pk': self.kwargs['pk']}
        )


class CategoryDeleteView(DeleteView):
    template_name = 'expenses/category_delete.html'
    model = Category
    success_url = reverse_lazy('expenses:category_list')

main_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'main_app/index.html'

profiles/views.py
from django.shortcuts import render

# Create your views here.

expenses/templates/expenses/category.html
{% extends 'main_app/layout.html' %}
{% block title %}Category list{% endblock %}

{% block header %}<h1>Category list</h1>{% endblock %}
{% block content %}
{% include 'main_app/nav.html' with page='category' %}

<table>
    <thead>
        <th>Name</th>
    </thead>
    <tbody>
        {% for category in category_list %}
        <tr>
            <td>{{ category.name }}</td>
            <td>
                <ul>
                    <li><a href="{% url 'expenses:category_detail' pk=category.pk %}">Detail</a></li>
                    <li><a href="{% url 'expenses:category_update' pk=category.pk %}">Update</a></li>
                    <li><a href="{% url 'expenses:category_delete' pk=category.pk %}">Delete</a></li>
                </ul>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{#<p align="left"><a href="{% url 'main_app:home' %}">Home</a>#}
<a href="{% url 'expenses:category_create' %}">Add category</a>
{% endblock %}

expenses/templates/expenses/category_create.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

expenses/templates/expenses/category_delete.html
<p>Are you really want to delete this category?</p>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Delete</button>
</form>

expenses/templates/expenses/category_detail.html
<style>
    table {
        border: solid black 1px;
    }
    table th {
        border: solid black 1px;
    }
    table td {
        border: solid black 1px
    }
</style>

{% if category %}
<table>
    <thead>
        <tr>
            <th>Title</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ category.name }}</td>
        </tr>
    </tbody>
</table>
{% else %}
<h1>No category found!</h1>
{% endif %}

<a href="{% url 'expenses:category_list' %}">Categories</a>
<a href="{% url 'main_app:home' %}">Home</a>

expenses/templates/expenses/category_update.html
{% extends 'main_app/layout.html' %}
{% block title %}Category update{% endblock %}
{% block header %}<h1>Category update</h1>{% endblock %}
{% block content %}

    <form method="POST">
        {% csrf_token %}

        <div class="form-group">
            {{ form.as_p }}
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>

{% endblock %}

expenses/templates/expenses/create.html
<form method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

expenses/templates/expenses/delete.html
<p>Are you really want to delete this category?</p>

<form method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Delete</button>
</form>

expenses/templates/expenses/detail.html
<style>
    table {
        border: solid black 1px;
    }
    table th {
        border: solid black 1px;
    }
    table td {
        border: solid black 1px
    }
</style>

{% if expense %}
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>When?</th>
            <th>Amount (BYN)</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ expense.name }}</td>
            <td>{{ expense.timestamp }}</td>
            <td>{{ expense.amount }}</td>
            <td>{{ expense.category|default:"Not defined" }}</td>
        </tr>
    </tbody>
</table>
{% else %}
<h1>No expenses found!</h1>
{% endif %}

expenses/templates/expenses/expenses_list.html
{% extends 'main_app/layout.html' %}
{% block title %}Expenses List{% endblock %}
{% block header %}<h1>Expenses List</h1>{% endblock %}
{% block content %}

    {% include "main_app/nav.html" with page='expenses' %}
    <table>
        <thead>
        <th>Name</th>
        <th>Timestamp</th>
        <th>Amount</th>
        <th>Category</th>
        <th></th>
        </thead>
        <tbody>
        {% for expense in expense_list %}
            <tr>
                <td>{{ expense.name }}</td>
                <td>{{ expense.timestamp }}</td>
                <td>{{ expense.amount }}</td>
                <td>{{ expense.category|default_if_none:'-----' }}</td>
                <td>
                    <ul>
                        <li><a href="{% url 'expenses:detail' pk=expense.pk %}">Detail</a></li>
                        <li><a href="{% url 'expenses:update' pk=expense.pk %}">Update</a></li>
                        <li><a href="{% url 'expenses:delete' pk=expense.pk %}">Delete</a></li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p align="left"><a href="{% url 'expenses:create' %}">Add expense</a></p>
{% endblock %}

expenses/templates/expenses/update.html
<from method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</from>
<p align="left"><a href="{% url 'expenses:category_create' %}">Add category</a></p>

main_app/templates/main_app/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'main_app/css/bootstrap.css' %}">

main_app/templates/main_app/index.html
{% extends 'main_app/layout.html' %}

{% block title %}Main Page{% endblock %}

{% block header %}
    <h1>Main Page</h1>
{% endblock %}

{% block content %}
{% include 'main_app/nav.html' with page='index' %}
{% endblock %}

main_app/templates/main_app/js.html
{% load static %}
<script src="{% static 'main_app/js/bootstrap.js' %}"></script>

main_app/templates/main_app/layout.html
<html>
    <head>
        <title>DjangoSample - {% block title %}{% endblock %}</title>
    <meta charset="utf-8">
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"#}
{#          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">#}

        {% include 'main_app/css.html' %}
        {% include 'main_app/js.html' %}
    </head>
    <body>
        <div class="container">
            {% block header %}{% endblock %}
            {% block content %}
            {% endblock %}
        </div>
        {% block custom_js %}{% endblock %}
        {% block custom_css %}{% endblock %}


{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"#}
{#            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"#}
{#            crossorigin="anonymous"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/axjax/libs/popper.js/1.14.3/umd/popper.min.js"#}
{#            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"#}
{#            crossorigin="anonymous"></script>#}
{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"#}
{#            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"#}
{#            crossorigin="anonymous"></script>#}
</body>
</html>

main_app/templates/main_app/nav.html
<ul>
    <li {% if page == 'expenses' %}class="active"{% endif %}>
        <a href="{% url 'expenses:list' %}">Expenses</a>
    </li>

    <li {% if page == 'category' %}class="active"{% endif %}>
        <a href="{% url 'expenses:category_list' %}">Category</a>
    </li>
</ul>

profiles/templates/profiles/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <img src="{{ object.avatar.url }}" alt="">
</head>
<body>

</body>
</html>

templates/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'main_app/css/bootstrap.css' %}">

templates/js.html
{% load static %}
<script src="{% static 'main_app/js/bootstrap.js' %}"></script>

templates/layout.html
<html>
    <head>
        <title>DjangoSample - {% block title %}{% endblock %}</title>
        {% include 'css.html' %}
        {% include 'js.html' %}
    </head>
    <body>
        <div class="container">
            {% block header %}{% endblock %}
            {% block content %}
            {% endblock %}
        </div>
        {% block custom_js %}{% endblock %}
        {% block custom_css %}{% endblock %}
    </body>
</html>